// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sg_pd
Rcpp::List sg_pd();
RcppExport SEXP RSGSolve_sg_pd() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sg_pd());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP RSGSolve_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// solve_rsg
SEXP solve_rsg(double delta, int numStates, Rcpp::List states, int allIterations, int verbose, int noreturn, double normtol, double directiontol, double leveltol, double improvetol);
RcppExport SEXP RSGSolve_solve_rsg(SEXP deltaSEXP, SEXP numStatesSEXP, SEXP statesSEXP, SEXP allIterationsSEXP, SEXP verboseSEXP, SEXP noreturnSEXP, SEXP normtolSEXP, SEXP directiontolSEXP, SEXP leveltolSEXP, SEXP improvetolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type numStates(numStatesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type states(statesSEXP);
    Rcpp::traits::input_parameter< int >::type allIterations(allIterationsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type noreturn(noreturnSEXP);
    Rcpp::traits::input_parameter< double >::type normtol(normtolSEXP);
    Rcpp::traits::input_parameter< double >::type directiontol(directiontolSEXP);
    Rcpp::traits::input_parameter< double >::type leveltol(leveltolSEXP);
    Rcpp::traits::input_parameter< double >::type improvetol(improvetolSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_rsg(delta, numStates, states, allIterations, verbose, noreturn, normtol, directiontol, leveltol, improvetol));
    return rcpp_result_gen;
END_RCPP
}
