# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sg_pd <- function() {
    .Call('RSGSolve_sg_pd', PACKAGE = 'RSGSolve')
}

rcpp_hello <- function() {
    .Call('RSGSolve_rcpp_hello', PACKAGE = 'RSGSolve')
}

solve_rsg <- function(delta, numStates, states, allIterations, normtol, directiontol, leveltol, improvetol) {
    .Call('RSGSolve_solve_rsg', PACKAGE = 'RSGSolve', delta, numStates, states, allIterations, normtol, directiontol, leveltol, improvetol)
}

